apiVersion: v2
appVersion: "7.2.1"
description: A Helm chart for Confluent Kafka on Kubernetes
name: kafka
version: 0.1.0
dependencies:
  - name: zookeeper
    version: 0.1.0
    repository: file://../zookeeper
    condition: zookeeper.enabled
